/**
 * Recruiter CRM — spreadsheet layer.
 * "Recruiters" tab: one row per company+recruiter, upserted (history preserved
 * in Notes is never overwritten). "Activity Log" tab: append-only timeline.
 * "_State" hidden tab: processed message ids + last run time.
 */

function getSpreadsheet() {
  var props = PropertiesService.getScriptProperties();
  var id = props.getProperty('SPREADSHEET_ID');
  if (id) {
    try { return SpreadsheetApp.openById(id); } catch (e) { /* recreate below */ }
  }
  var ss = SpreadsheetApp.create(CONFIG.SPREADSHEET_NAME);
  props.setProperty('SPREADSHEET_ID', ss.getId());
  initSheets(ss);
  return ss;
}

function initSheets(ss) {
  var rec = ss.getSheets()[0];
  rec.setName(CONFIG.SHEET_RECRUITERS);
  rec.getRange(1, 1, 1, RECRUITER_COLUMNS.length).setValues([RECRUITER_COLUMNS])
    .setFontWeight('bold');
  rec.setFrozenRows(1);

  var act = ss.insertSheet(CONFIG.SHEET_ACTIVITY);
  act.getRange(1, 1, 1, 5)
    .setValues([['Date', 'Company', 'Recruiter', 'Event', 'Details']])
    .setFontWeight('bold');
  act.setFrozenRows(1);

  var state = ss.insertSheet(CONFIG.SHEET_STATE);
  state.getRange(1, 1).setValue('processed_ids');
  state.hideSheet();
}

/* ---------------------------- state ---------------------------- */

function loadState(ss) {
  var props = PropertiesService.getScriptProperties();
  var sheet = ss.getSheetByName(CONFIG.SHEET_STATE) || initStateSheet(ss);
  var last = sheet.getLastRow();
  var ids = {};
  if (last >= 2) {
    sheet.getRange(2, 1, last - 1, 1).getValues().forEach(function (row) {
      if (row[0]) ids[row[0]] = true;
    });
  }
  return {
    lastRunTime: props.getProperty('LAST_RUN_TIME'),
    processedIds: ids,
    newIds: []
  };
}

function initStateSheet(ss) {
  var state = ss.insertSheet(CONFIG.SHEET_STATE);
  state.getRange(1, 1).setValue('processed_ids');
  state.hideSheet();
  return state;
}

function saveState(ss, state) {
  PropertiesService.getScriptProperties().setProperty('LAST_RUN_TIME', state.lastRunTime);
  if (state.newIds.length) {
    var sheet = ss.getSheetByName(CONFIG.SHEET_STATE);
    var rows = state.newIds.map(function (id) { return [id]; });
    sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, 1).setValues(rows);
    // Keep the ledger bounded: ids older than ~10k rows can't recur in searches.
    var excess = sheet.getLastRow() - 10001;
    if (excess > 0) sheet.deleteRows(2, excess);
  }
}

/* ------------------------- recruiters tab ------------------------- */

/**
 * Inserts or updates the row for this record's company+recruiter.
 * @return {Array} activity-log rows generated by this upsert.
 */
function upsertRecruiterRow(ss, record, state) {
  var sheet = ss.getSheetByName(CONFIG.SHEET_RECRUITERS);
  var col = colIndex();
  var key = rowKey(record.company, record.recruiterEmail);
  var activity = [];

  var last = sheet.getLastRow();
  var rowNum = 0;
  if (last >= 2) {
    var keys = sheet.getRange(2, 1, last - 1, RECRUITER_COLUMNS.length).getValues();
    for (var i = 0; i < keys.length; i++) {
      if (rowKey(keys[i][col.Company], keys[i][col['Recruiter Email']]) === key) {
        rowNum = i + 2;
        break;
      }
    }
  }

  var isNew = !rowNum;
  var existing = isNew
    ? RECRUITER_COLUMNS.map(function () { return ''; })
    : sheet.getRange(rowNum, 1, 1, RECRUITER_COLUMNS.length).getValues()[0];

  var out = existing.slice();
  fillIfBetter(out, col, 'Recruiter Name', record.recruiterName);
  fillIfBetter(out, col, 'Recruiter Email', record.recruiterEmail);
  fillIfBetter(out, col, 'Company', record.company);
  fillIfBetter(out, col, 'Job Title', record.jobTitle);
  fillIfBetter(out, col, 'Recruiter Title', record.recruiterTitle);
  fillIfBetter(out, col, 'Phone', record.phone);

  if (isNew || !existing[col['First Contact']]) out[col['First Contact']] = fmtDate(record.firstContact);
  out[col['Last Contact']] = fmtDate(record.lastContact);
  out[col['Interview Date(s)']] = record.interviewDates.map(fmtDateTime).join(', ');
  out[col['Next Interview']] = record.nextInterview ? fmtDateTime(record.nextInterview) : '';

  var oldStage = existing[col['Current Stage']];
  out[col['Current Stage']] = record.stage;

  if (isNew) {
    sheet.appendRow(out);
    activity.push([fmtDate(record.firstContact), record.company, record.recruiterName,
      'New contact', record.lastSubject]);
  } else {
    sheet.getRange(rowNum, 1, 1, out.length).setValues([out]);
    if (oldStage && oldStage !== record.stage) {
      activity.push([fmtDate(new Date()), record.company, record.recruiterName,
        'Stage: ' + oldStage + ' → ' + record.stage, record.lastSubject]);
    }
  }

  // Log each never-before-seen message as an activity entry.
  record.messageIds.forEach(function (id, idx) {
    if (state.processedIds[id]) return;
    state.processedIds[id] = true;
    state.newIds.push(id);
    if (!isNew || idx > 0) { // the "New contact" entry already covers message 0
      activity.push([fmtDate(idx === record.messageIds.length - 1 ? record.lastContact : record.firstContact),
        record.company, record.recruiterName, 'Email', record.lastSubject]);
    }
  });

  return activity;
}

/**
 * After email processing, sweep the whole Recruiters tab and update interview
 * columns from the calendar — catches interviews added straight to Calendar.
 * Newly seen events are logged to the Activity tab.
 */
function refreshCalendarColumns(ss, events, state, activityOut) {
  var sheet = ss.getSheetByName(CONFIG.SHEET_RECRUITERS);
  var last = sheet.getLastRow();
  if (last < 2) return;

  var col = colIndex();
  var range = sheet.getRange(2, 1, last - 1, RECRUITER_COLUMNS.length);
  var rows = range.getValues();

  rows.forEach(function (row) {
    var pseudo = { company: row[col.Company], recruiterEmail: row[col['Recruiter Email']] };
    var matched = eventsForRecord(pseudo, events);
    if (!matched.length) return;

    row[col['Interview Date(s)']] = matched.map(function (ev) { return fmtDateTime(ev.start); }).join(', ');
    var upcoming = matched.filter(function (ev) { return ev.start > new Date(); });
    row[col['Next Interview']] = upcoming.length ? fmtDateTime(upcoming[0].start) : '';

    matched.forEach(function (ev) {
      if (state.processedIds[ev.id]) return;
      state.processedIds[ev.id] = true;
      state.newIds.push(ev.id);
      activityOut.push([fmtDate(ev.start), row[col.Company], row[col['Recruiter Name']],
        'Interview scheduled', ev.title + ' @ ' + fmtDateTime(ev.start)]);
    });
  });

  range.setValues(rows);
}

/* ------------------------- activity tab ------------------------- */

function appendActivity(ss, entries) {
  if (!entries.length) return;
  var sheet = ss.getSheetByName(CONFIG.SHEET_ACTIVITY);
  entries.sort(function (a, b) { return String(a[0]).localeCompare(String(b[0])); });
  sheet.getRange(sheet.getLastRow() + 1, 1, entries.length, 5).setValues(entries);
}

/* ------------------------- helpers ------------------------- */

function colIndex() {
  var idx = {};
  RECRUITER_COLUMNS.forEach(function (name, i) { idx[name] = i; });
  return idx;
}

function rowKey(company, email) {
  return String(company || '').toLowerCase().trim() + '|' + String(email || '').toLowerCase().trim();
}

/** Only overwrite a cell when the new value is non-empty and the old one is empty or shorter-and-generic. */
function fillIfBetter(row, col, name, value) {
  if (!value) return;
  var cur = row[col[name]];
  if (!cur || (name === 'Recruiter Name' && String(cur).indexOf('@') !== -1)) {
    row[col[name]] = value;
  }
}

function fmtDate(d) {
  return Utilities.formatDate(new Date(d), Session.getScriptTimeZone(), 'yyyy-MM-dd');
}

function fmtDateTime(d) {
  return Utilities.formatDate(new Date(d), Session.getScriptTimeZone(), 'yyyy-MM-dd h:mm a');
}
